[package]
name = "emacs-greeting"
version = "0.1.0"
edition = "2018"
authors = ["Nguyễn Tuấn Anh <ubolonton@gmail.com>"]
publish = false

[dependencies]
emacs = "0.7.0"

[lib]
crate-type = ["cdylib"]
