[package]
name = "emacs-canvas-demo"
version = "0.1.0"
edition = "2024"
authors = ["Nguyễn Tuấn Anh <ubolonton@gmail.com>"]
publish = false

[dependencies]
# TODO: Use a crates.io version once `emacs-32-experimental` is released. Until then, this needs a
# checkout of emacs-module-rs with the canvas binding next to this repo.
emacs = { path = "../../emacs-module-rs", features = ["emacs-32-experimental"] }

[lib]
crate-type = ["cdylib"]
